# Generated by Django 5.1.6 on 2025-04-12 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_location', models.CharField(blank=True, choices=[('', ' '), ('kitchen', 'KITCHEN'), ('laundry', 'LAUNDRY ROOM'), ('living_room', 'LIVING ROOM'), ('bathroom', 'BATHROOM'), ('office', 'OFFICE')], max_length=50)),
                ('prod_category', models.CharField(blank=True, max_length=255)),
                ('prod_type', models.CharField(blank=True, max_length=255)),
                ('prod_name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('stock', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
